#!/usr/bin/env python3
#
# Mother Nature - Metis Feedback System Integration
#
# ------------------------------------------------

# Python Internals
# ----------------
import os
import json
import yaml
import subprocess
import tempfile
import shutil
from pathlib import Path
from typing import Dict, List, Optional, Union
import asyncio
import threading

# Python Externals
# ----------------
import pandas as pd
import numpy as np
from datetime import datetime

# Discord Imports
# ---------------
import discord
from discord.ext import commands

# Github Imports
# --------------
from github import Github

class MetisFeedbackSystem:
    """
    Metis Feedback System Integration for Mother Nature
    
    This class handles the integration between Mother Nature Discord bot
    and the Metis GUI for collecting expert feedback on generated molecules.
    """
    
    def __init__(self, github: Github, repo, global_chem_repo, client, bot):
        """
        Initialize the Metis Feedback System
        
        Args:
            github: GitHub API instance
            repo: Repository instance for private workers
            global_chem_repo: Global-Chem repository instance
            client: Discord client instance
            bot: Discord bot instance
        """
        self.github = github
        self.repo = repo
        self.global_chem_repo = global_chem_repo
        self.client = client
        self.bot = bot
        
        # Feedback system configuration
        self.feedback_config = {
            'metis_path': os.getenv('METIS_PATH', 'metis'),
            'feedback_data_dir': 'feedback_data',
            'max_molecules_per_session': 50,
            'supported_categories': [
                'cannabis', 'medicinal_chemistry', 'food', 'environment',
                'space', 'materials', 'narcotics', 'global', 'contraceptives',
                'performance_enhancements', 'solar_cells', 'education'
            ]
        }
        
        # Create feedback data directory
        self._ensure_feedback_directory()
        
    def _ensure_feedback_directory(self):
        """Ensure feedback data directory exists"""
        feedback_dir = Path(self.feedback_config['feedback_data_dir'])
        feedback_dir.mkdir(exist_ok=True)
        
        # Create category subdirectories
        for category in self.feedback_config['supported_categories']:
            category_dir = feedback_dir / category
            category_dir.mkdir(exist_ok=True)
            
    def create_metis_config(self, category: str, num_molecules: int = 20) -> str:
        """
        Create Metis configuration file for feedback collection
        
        Args:
            category: Chemical category for feedback collection
            num_molecules: Number of molecules to show for feedback
            
        Returns:
            Path to the created configuration file
        """
        config = {
            'seed': 42,
            'tutorial': False,
            'debug': False,
            'max_iterations': 1,
            'innerloop_iterations': None,
            'activity_label': f'feedback_{category}',
            'introText': f'Please provide feedback on {category} molecules generated by Mother Nature AI.',
            'propertyLabels': {
                'activity': 'Overall Quality',
                'ugly': 'Mutagenicity',
                'tox': 'Toxicity',
                'stability': 'Stability',
                'like': 'Desirable Properties'
            },
            'data': {
                'initial_path': f'{self.feedback_config["feedback_data_dir"]}/{category}/initial_molecules.csv',
                'path': f'{self.feedback_config["feedback_data_dir"]}/{category}/scaffold_memory.csv',
                'selection_strategy': 'random',
                'num_molecules': num_molecules,
                'run_name': f'mother_nature_feedback_{category}_{datetime.now().strftime("%Y%m%d_%H%M%S")}'
            },
            'ui': {
                'show_atom_contributions': {
                    'render': True,
                    'path': None,
                    'ECFP': {
                        'bitSize': 2048,
                        'radius': 2,
                        'useCounts': False
                    }
                },
                'show_reference_molecules': {
                    'render': False,
                    'path': None,
                    'ECFP': None
                },
                'tab': {
                    'render': True,
                    'tab_names': ['Molecule View', 'Properties', 'Feedback']
                },
                'navigationbar': {
                    'sendButton': {'render': True},
                    'editButton': {'render': True}
                },
                'general': {
                    'render': True,
                    'slider': True
                },
                'substructures': {
                    'render': True,
                    'liabilities': {
                        'ugly': {
                            'name': 'Mutagenicity',
                            'color': '#ff7f7f'
                        },
                        'tox': {
                            'name': 'Toxicity',
                            'color': '#51d67e'
                        },
                        'stability': {
                            'name': 'Stability',
                            'color': '#eed358'
                        },
                        'like': {
                            'name': 'Desirable Properties',
                            'color': '#9542f5'
                        }
                    }
                },
                'global_properties': {
                    'render': True,
                    'liabilities': ['activity', 'ugly', 'tox', 'stability', 'like']
                }
            },
            'de_novo_model': None,
            'reward_model': None
        }
        
        # Create config file
        config_path = f'{self.feedback_config["feedback_data_dir"]}/{category}/metis_config.yml'
        with open(config_path, 'w') as f:
            yaml.dump(config, f, default_flow_style=False)
            
        return config_path
        
    def prepare_molecules_for_feedback(self, category: str, smiles_list: List[str], 
                                     names: Optional[List[str]] = None) -> str:
        """
        Prepare molecules for feedback collection in Metis format
        
        Args:
            category: Chemical category
            smiles_list: List of SMILES strings
            names: Optional list of molecule names
            
        Returns:
            Path to the prepared CSV file
        """
        if names is None:
            names = [f'molecule_{i+1}' for i in range(len(smiles_list))]
            
        # Create DataFrame in Metis format
        df = pd.DataFrame({
            'SMILES': smiles_list,
            'Name': names,
            'activity': [0.5] * len(smiles_list),  # Default neutral score
            'ugly': [0.0] * len(smiles_list),
            'tox': [0.0] * len(smiles_list),
            'stability': [0.0] * len(smiles_list),
            'like': [0.0] * len(smiles_list)
        })
        
        # Save to CSV
        output_path = f'{self.feedback_config["feedback_data_dir"]}/{category}/initial_molecules.csv'
        df.to_csv(output_path, index=False)
        
        return output_path
        
    async def collect_feedback(self, channel_name: str, category: str, 
                             num_molecules: int = 20) -> str:
        """
        Start Metis GUI for feedback collection
        
        Args:
            channel_name: Discord channel name
            category: Chemical category for feedback
            num_molecules: Number of molecules to show
            
        Returns:
            Status message
        """
        try:
            # Validate category
            if category not in self.feedback_config['supported_categories']:
                return f"Error: Category '{category}' not supported. Supported categories: {', '.join(self.feedback_config['supported_categories'])}"
                
            # Get molecules from Global-Chem for the category
            molecules = await self._get_molecules_for_category(category, num_molecules)
            
            if not molecules:
                return f"No molecules found for category '{category}'. Please ensure the category has molecules in Global-Chem."
                
            # Prepare molecules for feedback
            smiles_list = [mol['smiles'] for mol in molecules]
            names = [mol['name'] for mol in molecules]
            
            csv_path = self.prepare_molecules_for_feedback(category, smiles_list, names)
            
            # Create Metis configuration
            config_path = self.create_metis_config(category, num_molecules)
            
            # Start Metis GUI in a separate thread
            def run_metis():
                try:
                    output_dir = f'{self.feedback_config["feedback_data_dir"]}/{category}/feedback_results'
                    subprocess.run([
                        self.feedback_config['metis_path'],
                        '-f', config_path,
                        '--output', output_dir
                    ], check=True)
                except subprocess.CalledProcessError as e:
                    print(f"Metis GUI error: {e}")
                except FileNotFoundError:
                    print("Metis not found. Please install Metis first.")
                    
            # Run Metis in background thread
            thread = threading.Thread(target=run_metis)
            thread.daemon = True
            thread.start()
            
            return f"Metis feedback GUI started for category '{category}' with {len(molecules)} molecules. Please provide feedback in the GUI window."
            
        except Exception as e:
            return f"Error starting feedback collection: {str(e)}"
            
    async def _get_molecules_for_category(self, category: str, num_molecules: int) -> List[Dict]:
        """
        Get molecules from Global-Chem for a specific category
        
        Args:
            category: Chemical category
            num_molecules: Number of molecules to retrieve
            
        Returns:
            List of molecule dictionaries
        """
        try:
            # This would typically fetch from Global-Chem database
            # For now, return sample data
            sample_molecules = [
                {'smiles': 'CC(=O)OC1=CC=CC=C1C(=O)O', 'name': 'Aspirin'},
                {'smiles': 'CC(C)CC1=CC=C(C=C1)C(C)C(=O)O', 'name': 'Ibuprofen'},
                {'smiles': 'CC1=C(C(=CC=C1)NC(=O)C2=CC=C(C=C2)CN3CCN(CC3)C)NC4=NC=CC(=N4)C5=CN=CC=C5', 'name': 'Gefitinib'}
            ]
            
            return sample_molecules[:num_molecules]
            
        except Exception as e:
            print(f"Error fetching molecules for category {category}: {e}")
            return []
            
    async def process_feedback_results(self, category: str) -> str:
        """
        Process feedback results from Metis session
        
        Args:
            category: Chemical category
            
        Returns:
            Status message with feedback summary
        """
        try:
            feedback_dir = Path(f'{self.feedback_config["feedback_data_dir"]}/{category}/feedback_results')
            
            if not feedback_dir.exists():
                return f"No feedback results found for category '{category}'"
                
            # Look for feedback CSV files
            feedback_files = list(feedback_dir.glob('*.csv'))
            
            if not feedback_files:
                return f"No feedback data files found in {feedback_dir}"
                
            # Process the most recent feedback file
            latest_file = max(feedback_files, key=lambda x: x.stat().st_mtime)
            
            df = pd.read_csv(latest_file)
            
            # Analyze feedback
            total_molecules = len(df)
            molecules_with_feedback = len(df[df['activity'] != 0.5])
            
            # Calculate average scores
            avg_activity = df['activity'].mean()
            avg_toxicity = df['tox'].mean()
            avg_stability = df['stability'].mean()
            
            # Create feedback summary
            summary = f"""
Feedback Summary for {category}:
- Total molecules reviewed: {total_molecules}
- Molecules with feedback: {molecules_with_feedback}
- Average activity score: {avg_activity:.3f}
- Average toxicity score: {avg_toxicity:.3f}
- Average stability score: {avg_stability:.3f}
- Feedback file: {latest_file.name}
            """.strip()
            
            return summary
            
        except Exception as e:
            return f"Error processing feedback results: {str(e)}"
            
    async def create_feedback_issue(self, category: str, feedback_summary: str) -> str:
        """
        Create GitHub issue with feedback results
        
        Args:
            category: Chemical category
            feedback_summary: Summary of feedback results
            
        Returns:
            Status message
        """
        try:
            issue_title = f"Feedback Results: {category} - {datetime.now().strftime('%Y-%m-%d %H:%M')}"
            
            issue_body = f"""
## Mother Nature Feedback System Results

**Category:** {category}
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

### Feedback Summary
```
{feedback_summary}
```

### Next Steps
- Review feedback data
- Update training dataset
- Retrain REINVENT model if needed
- Generate new molecules based on feedback

---
*Generated by Mother Nature Feedback System*
            """.strip()
            
            # Create issue in Global-Chem repository
            issue = self.global_chem_repo.create_issue(
                title=issue_title,
                body=issue_body,
                labels=['feedback', 'mother-nature', category]
            )
            
            return f"Feedback issue created: {issue.html_url}"
            
        except Exception as e:
            return f"Error creating feedback issue: {str(e)}"
            
    def get_feedback_status(self, category: str = None) -> str:
        """
        Get status of feedback collection for categories
        
        Args:
            category: Specific category to check (optional)
            
        Returns:
            Status message
        """
        try:
            if category:
                categories = [category]
            else:
                categories = self.feedback_config['supported_categories']
                
            status_lines = []
            
            for cat in categories:
                feedback_dir = Path(f'{self.feedback_config["feedback_data_dir"]}/{cat}')
                
                if feedback_dir.exists():
                    # Count feedback files
                    feedback_files = list(feedback_dir.glob('feedback_results/*.csv'))
                    status_lines.append(f"- {cat}: {len(feedback_files)} feedback sessions")
                else:
                    status_lines.append(f"- {cat}: No feedback data")
                    
            return "Feedback System Status:\n" + "\n".join(status_lines)
            
        except Exception as e:
            return f"Error getting feedback status: {str(e)}" 